### ISSUE TITLE
Coverage parameter?

### ISSUE THREAD

**Issue by Anto007** [NuruddinKhoiry/blastMining#1]
This looks like an interesting tool and I'm looking forward to testing it out. Before going ahead with the testing, I was just curious if your tool has a coverage cutoff parameter too, for example query coverage or query/hit coverage?

**Comment by NuruddinKhoiry** [comment]
Hi Jubin

I am really sorry for my late reply. I had many exams a few days ago.

I appreciate your interest in testing this tool.
Unfortunately, I haven't included the query/hit coverage parameter in the mining algorithm. However, you can still add it when you run the blastn program. 

For example:
In the "full_pipeline" mode, you can use -bp option and specify the query/hit coverage. e.g., -bp "-qcov_hsp_perc 80"

$blastMining full_pipeline \
	-i ASV.fasta \
	-o vote_pipe \
	-bp "-db nt -max_target_seqs 10 -num_threads 5 -qcov_hsp_perc 80" \
	-m vote \
	-e 0.001 \
	-txl 99,97,95,90,85,80,75 \
	-n 10 \
	-sm 'Sample' \
	-j 8 \
	-p lca_method \
	-kp \
	-rm

Best regards
Khoiri

**Comment by Anto007** [comment]
No worries @NuruddinKhoiry and many thanks for your response. Sure, I can just stick to the coverage parameter in blastn
